/** Every ECG the game can draw, in teaching order. */
import {
  brugada,
  hyperkalaemia,
  hypokalaemia,
  lbbb,
  longQt,
  lvh,
  pericarditis,
  pulmonaryEmbolism,
  rbbb,
  rhythms,
  sinus,
  stemi,
  tcaToxicity,
  wpw,
  type EcgSpec,
} from './model'

export const ATLAS: (() => EcgSpec)[] = [
  () => sinus(),
  rhythms.sinusTachy,
  rhythms.sinusBrady,
  rhythms.firstDegree,
  rhythms.mobitz1,
  rhythms.mobitz2,
  rhythms.chb,
  () => rhythms.af(),
  () => rhythms.flutter(),
  () => rhythms.svt(),
  () => rhythms.vt(),
  rhythms.torsades,
  rhythms.vf,
  rhythms.asystole,
  () => rhythms.paced(true),
  () => rhythms.paced(false),
  rhythms.junctional,
  () => stemi('inferior'),
  () => stemi('anterior'),
  () => stemi('anterolateral'),
  () => stemi('lateral'),
  () => stemi('posterior'),
  () => hyperkalaemia('mild'),
  () => hyperkalaemia('moderate'),
  () => hyperkalaemia('severe'),
  () => hypokalaemia(),
  () => lbbb(),
  () => rbbb(),
  () => pericarditis(),
  pulmonaryEmbolism,
  () => lvh(),
  () => brugada(),
  () => wpw(),
  tcaToxicity,
  () => longQt(),
]
