/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GymRouteImport } from './routes/gym'
import { Route as BadgePackIdRouteImport } from './routes/badge/$packId'
import { Route as DebriefPackIdRouteImport } from './routes/debrief/$packId'
import { Route as PlayPackIdRouteImport } from './routes/play/$packId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GymRoute = GymRouteImport.update({
  id: '/gym',
  path: '/gym',
  getParentRoute: () => rootRouteImport,
} as any)
const BadgePackIdRoute = BadgePackIdRouteImport.update({
  id: '/badge/$packId',
  path: '/badge/$packId',
  getParentRoute: () => rootRouteImport,
} as any)
const DebriefPackIdRoute = DebriefPackIdRouteImport.update({
  id: '/debrief/$packId',
  path: '/debrief/$packId',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayPackIdRoute = PlayPackIdRouteImport.update({
  id: '/play/$packId',
  path: '/play/$packId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/gym': typeof GymRoute
  '/badge/$packId': typeof BadgePackIdRoute
  '/debrief/$packId': typeof DebriefPackIdRoute
  '/play/$packId': typeof PlayPackIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/gym': typeof GymRoute
  '/badge/$packId': typeof BadgePackIdRoute
  '/debrief/$packId': typeof DebriefPackIdRoute
  '/play/$packId': typeof PlayPackIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/gym': typeof GymRoute
  '/badge/$packId': typeof BadgePackIdRoute
  '/debrief/$packId': typeof DebriefPackIdRoute
  '/play/$packId': typeof PlayPackIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/gym' | '/badge/$packId' | '/debrief/$packId' | '/play/$packId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/gym' | '/badge/$packId' | '/debrief/$packId' | '/play/$packId'
  id:
    | '__root__'
    | '/'
    | '/gym'
    | '/badge/$packId'
    | '/debrief/$packId'
    | '/play/$packId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GymRoute: typeof GymRoute
  BadgePackIdRoute: typeof BadgePackIdRoute
  DebriefPackIdRoute: typeof DebriefPackIdRoute
  PlayPackIdRoute: typeof PlayPackIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gym': {
      id: '/gym'
      path: '/gym'
      fullPath: '/gym'
      preLoaderRoute: typeof GymRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/badge/$packId': {
      id: '/badge/$packId'
      path: '/badge/$packId'
      fullPath: '/badge/$packId'
      preLoaderRoute: typeof BadgePackIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debrief/$packId': {
      id: '/debrief/$packId'
      path: '/debrief/$packId'
      fullPath: '/debrief/$packId'
      preLoaderRoute: typeof DebriefPackIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/$packId': {
      id: '/play/$packId'
      path: '/play/$packId'
      fullPath: '/play/$packId'
      preLoaderRoute: typeof PlayPackIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GymRoute: GymRoute,
  BadgePackIdRoute: BadgePackIdRoute,
  DebriefPackIdRoute: DebriefPackIdRoute,
  PlayPackIdRoute: PlayPackIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
